---
title: "Inicio"
author: " "
output:
    html_document:
        smart: false
        theme: united
        highlight: tango
        includes:
          before_body: header.html
#          after_body: footer.html

---

<!---
Para rendir el sitio desde terminal R:
rmarkdown::render_site(encoding = 'UTF-8')
--->

<br/>
<br/>

# **Curso Estadística multivariada - 1er sem 2019**
Web link: [http://bit.ly/multivariada](http://bit.ly/multivariada)

<br/>

## **Departamento de Sociología, Facultad de Ciencias Sociales - Universidad de Chile**

<br/>

<div class="alert alert-info">
  <strong>NOVEDADES (actualizadas 15 Mayo)</strong>

  - Fecha controles recuperativos: 27 de Mayo 8:30
  - Actualización pauta trabajo: detalles sobre mínimos entrega 1
  - Lunes 20 no hay clases
  - Actualización documento programación de sesiones
  - Notas control 1:
    - [Pauta](documents/controles/Control1_pauta.html)
    - [Notas seccion 1](http://bit.ly/2V8ejHm)
    - [Notas seccion 2](http://bit.ly/2V5xgdF)

</div>



<br/>

## **Equipo**:

<br/>

### _Profesores_

  - Juan Carlos Castillo, juancastillov@uchile.cl - [jc-castillo.com](https://jc-castillo.com)
  - Alejandro Plaza, agplaza@uc.cl

<br/>

### _Ayudantes_
  - Anaís Herrera
  - Carlos Budnevich
  - Francisco Meneses
  - Gabriel Sotomayor
  - Matías Montero
  - Simón Varas
  - Sofía Villalobos


<br/>
<br/>

## **Programación**

El programa oficial del curso se puede bajar [aquí](documents/programa/Estadística Multivariada_programa.pdf)

La programación de las sesiones se encuentra [aquí](documents/programa/Multiv2019prog_sesiones.pdf)
