---
title: "Practicas"
author: " "
output:
    html_document:
        theme: united

---
<br/>

### Prácticas

- [1: Regresión Simple 1: Primera estimación](documents/practicas/1_regsimp/prac1_regsimp.html)

<br/>

- [2: Regresión Simple 2: Ajuste general, residuos y correlación](documents/practicas/2regsimp/prac2_regsimp1.html)

<br/>

- [3: Regresión Múltiple: Control y parcialización correlación](documents/practicas/3regmul/Practica_3regmul2.html)

<br/>

- [4: Regresión Múltiple: categoricos e inferencia](documents/practicas/4regmul/prac_4regmul2.html)

<br/>

- [5: Regresión Múltiple: comparación de modelos](documents/practicas/8commodel/prac_5commodel.html)

<br/>

- [6: Regresión logística](documents/practicas/6intrologit/prac_6intrologit.html)

<br/>

- [7: Diagnóstico supuestos](documents/practicas/8diagnostico/prac_8doagnostico.html)


<br/>

### Talleres/ Ayudantías

- [Taller n°1: Manejo de bases de datos en R (abrir, filtrar, recodificar, descriptivos básicos, creación de índices y correlación de Pearson).](documents/ayudantias/Taller_1_Estadística_multivariada.R)
