---
title: "Trabajos"
author: " "
output:
    html_document:
      theme: united
      toc: true
      toc_float: true
      toc_depth: 2

---
# Pauta trabajo Estadística Multivariada

## Objetivo general
Aplicar los contenidos del curso a una temática de interés en formato de artículo de investigación breve.

## Sobre los temas
Para poder lograr un mayor foco y colaboración en temáticas específicas, así como también facilitar el proceso de asesorías, se proponen fuentes de datos específicas con las cuales realizar los trabajos:

- [ELSOC](http://www.elsoc.cl/) (Ola 1)
  - [Cuestionario Ola 1](http://www.elsoc.cl/wp-content/uploads/2017/05/Cuestionario_ELSOC_Ola_01_Completo.pdf)
  - [Libro de códigos Ola 1](http://www.elsoc.cl/wp-content/uploads/2017/05/Libro_de_Codigos_ELSOC_Ola_01_Completo.pdf)
  - [base de datos Ola 1](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0KIRBJ&version=2.0)
- [CASEN](http://observatorio.ministeriodesarrollosocial.gob.cl/casen-multidimensional/casen/basedatos.php) (evt. subset)
- [SIMCE](https://www.agenciaeducacion.cl/evaluaciones/que-es-el-simce/) (evt. subset)
- [LAPOP](https://www.vanderbilt.edu/lapop-espanol/) - OLA 2016
- [Desiguales](https://www.desiguales.org/descripcin-del-libro)
- CEP Chile - ISSP
  - 2016 [Rol del gobierno](https://dbk.gesis.org/dbksearch/sdesc2.asp?no=6900&db=E&tab=3)
  - 2017 [Redes sociales](https://dbk.gesis.org/DBKsearch/SDESC2.asp?no=6980&tab=3&db=E)
- * eventualmente otras bases

## Modalidad de trabajo y asesorías

Los trabajos por regla general se realizarán en duplas, a menos que se justifique una situación diferente.

En el caso de ser **tres integrantes**, se exigirá que al menos se trabaje con dos variables dependientes.

Las duplas se inscribirán hasta la semana del 15 de Abril con un tema / base de datos específica a trabajar.


## Formato entregas

Este trabajo posee dos entregas, tal como se señala en el programa del curso: un informe de avance (20% nota final) y un informe final (30%). El informe final debe tener formato de artículo/reporte breve de investigación, con las siguientes secciones y número de palabras sugeridas (total máximo 3.500):

1. Título: Breve, lo principal es hacer alusión al objeto central de estudio (variable dependiente)


2. Abstract (250 palabras), incluye: problema/pregunta, objetivo, datos (y N), resultado principal.


3. Introducción: definición de la problemática a abordar, su relevancia y principales conceptos (500 palabras).

En este apartado es importante considerar:

- Relevancia del tema de investigación
- Relevancia del problema de investigación: además de que el "tema" pueda ser relevante (ej: aumento de desigualdad económica, disminución de niveles de participación), la relevancia del problema se refiere a cuál es el aporte distintivo de este estudio desde una perspectiva académica y disciplinar (sociología).
- Precisar el concepto central que se va a investigar: Ejemplo "vamos a estudiar participación informal, entendiendo por ello la frecuencia de participación en actividades como marchas, boycotts y en redes sociales".
- Precisar argumento / hipótesis central "proponemos que a medida que aumenta el nivel de contactos con identificación política de izquierda, aumenta la participación política informal"
- El resto de la introducción usualmente se divide en dos secciones, que también son referidas como marco teórico, marco referencial, revisión bibliográfica, etc.
  - El primer apartado corresponde al objeto central de estudio /variable dependiente (explanandum), donde se profundiza en su origen y definición, y se revisan las principales investigaciones que se asocian a este concepto.
  - El segundo apartado corresponde a los conceptos relacionados con la variable dependiente (explanans) y en los cuales se basan las hipótesis. Se revisan en orden de relevancia.

4. Objetivos / hipótesis (alrededor de 3) (250 palabras)
5. Metodología: datos (no olvidar número de casos), variables y métodos  (500 palabras)
- Esta sección también incluye una tabla de descriptivos básicos, y una descripción detallada de la operacionalización y medición de las variables

6. Análisis (1500 palabras)
Comenzar con análisis descriptivo uni y bivariado, luego presentar las tablas de regresión.

7. Discusión de los resultados, con énfasis en la relación entre variable dependiente e independientes, limitaciones, posibles estudios futuros. (500 palabras)

Notas básicas de escritura académica:

- Una idea por párrafo
- Uso de "oración principal" (topic sentence): usualmente es la oración al principio del párrafo, que resume el sentido del párrafo completo y que conecta con el párrafo anterior.

---

Para el informe de avance se espera un reporte de alrededor de 1500-2000 palabras que sea una especie de borrador del informe final. La idea es avanzar en todas las secciones, incluyendo la temática general a abordar así como también datos y variables en la sección de métodos, y análisis descriptivos. El énfasis en esta primera entrega se encuentra en el planteamiento de las hipótesis y el modelo de regresión asociado, incluyendo una primera estimación. En el caso de los trabajos donde la variable dependiente sea dicotómica, para esta primera entrega la estimación puede ser realizada preliminarmente con OLS, y para la segunda se espera estimación con regresión logística. En la segunda entrega se corrigen los aspectos críticos según la primera evaluación, y se profundiza en chequeo de supuestos, casos influyentes e interacciones.

Formato:

- el formato recomendado es (R)Markdown, que facilita la integración y reproducibilidad de los análisis en R (<http://rusersgroup.com/blog/rmarkdown/>). Se pondrá a disposición una plantilla para realizar el trabajo en este formato.
- si se prefiere entregar en formato tradicional, es tamaño carta letra times new roman 12 (o equivalente) espacio 1,5, 3 cm márgenes laterales; en archivo pdf.
- referencias APA o Chicago.

## Fechas importantes

- Lunes 15 de Abril: inscripción de temas
- Lunes 20 Mayo: informe de avance (20%).
- Lunes 17 Junio: informe final (30%)

# Grupos y temas

## [Sección 1](https://docs.google.com/spreadsheets/d/1QAMuuaBQIverj3U2SHrhQWyMcNnc8_cw4452Z8jT-Ns/edit?usp=sharing)
## Sección 2


# Ejemplos

- [Ortiz-Inostroza, C., & López, E. (2017). Explorando modelos estadísticos para explicar la participación en protestas en Chile. Revista de Sociología, (32), pp. 13-31. doi:10.5354/0719-529X.2017.47883](https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47883/50542
)

- [Cereceda-Marambio, K., & Torres-Solís, A. (2017). Satisfacción con la democracia en Chile: De lo normativo a lo valorativo. Revista de Sociología, (32), pp. 32-49. doi:10.5354/0719-529X.2017.47884] (https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47884/50543)


## Con regresión logística

- [Gayo Cal, M. G., Cabrol, G. O., & Méndez, M. L. (2019). Elección escolar y selección de familias: reproducción de la clase media alta en Santiago de Chile. Revista Internacional de Sociología, 77(1), 120. https://doi.org/10.3989/ris.2019.77.1.17.310](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1020/1338)

- [Delfini, M. (2013) La afiliación sindical en Argentina. Análisis sobre sus determinantes. Revista Internacional de Sociología, 71(1)91-114,  http://dx.doi.org/10.3989/ris.2012.01.24.](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/485/507)
