---
title: "Pauta Control 2 Estadística Multivariada"
author: "Juan Carlos Castillo y Alejandro Plaza"
date: "28 de Mayo de 2019"
output: html_document
---

Preguntas (1 punto c/u):

**1.¿Qué información nos entrega el modelo 1 en términos de la relación entre las variables y su significación estadística?**

1.1. Relación negativa entre ingreso  preferencias por la redistribución: por cada 100.000 pesos de ingreso adicional las preferencias por redistribución disminuyen en -0.04 puntos. (0.5p)

1.2. Este coeficiente es estadísticamente significativo, se rechaza la hipótesis nula con un nivel de probabilidad de error (valor p) menor a 0.05. (0.5p)

**2.¿Qué información nos entrega el modelo 2 en términos del valor del coeficiente asociado a número de hijos, significación estadística y control estadístico?**

2.1. Relación positiva entre número de hijos y preferencias redistributivas: por cada hijo adicional las preferencias redistributivas aumentan en 0.04 puntos. Este valor es estadísticamente significativo con un valor p menor a 0.01 (0.5p)

2.2. Al mantener el número de hijos constante (o controlando por el número de hijos, o ceteris paribus), el coeficiente de ingreso deja de ser significativo en relación a las preferencias redistributivas. (0.5p)

**3.¿Cómo se puede interpretar el modelo 3 en términos del valor de los coeficientes asociados a ideología política?**

3.1. Las personas que se identifican con el centro tienen en promedio 0.2 puntos más en preferencias redistributivas que los que se identifican con la derecha (0.5p)

3.2. Las personas que se identifican con la izquierda tienen en promedio 0.28 puntos más en preferencias redistributivas que los que se identifican con la derecha (0.5p)

**4- Al estandarizar los coeficientes de las variables hijos e ingreso en el modelo 2 obtenemos -0.09 y 0.06 respectivamente. ¿Cómo se interpreta esta información?**

4.1. Por un aumento de una desviación estándar en número de hijos las preferencias redistributivas disminuyen -0.09 desviaciones estándar, (0.4p)

4.2. Por cada desviación estandar de ingresos las preferencias redistributivas aumentan 0.06 desviaciones estándar (0.4p)

4.3. Ambos efectos se pueden comparar dado que se encuentran en una misma unidad (ds), por lo tanto el tamaño del efecto de los hijos es mayor que el de los ingresos (0.2p)

**5.Suponiendo que el contraste efectuado entre el modelo 1 y el 2 mediante prueba F no es estadísticamente significativo, ¿Qué se concluye?**

- Que el modelo 2 no posee mejor ajuste que el modelo 1. (1p)

**6.Comente el ajuste general de los modelos en términos comparativos y de varianza explicada.**

El modelo 1 con la variable ingreso explica el 2% de la varianza de preferencias redistributivas. Esto aumenta al incorporar hijos a un 4%, y a un 10% al incorporar identificación política (basado en el R2 ajustado) (1p)
